name: Detector Test
on: [push]
jobs:
  testing in docker container:
    runs-on: ubuntu-20.04
    # container:
    #   image: opencvcourses/opencv-docker:latest
    name: Test Project
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action

      - uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: |
          docker build -t test_detector .
      - name: Run Tests in Container
        run: |
          docker run -v $PWD -w /workspaces/face_eyes_detectortest_detector /bin/bash -c "cmake -S . -B build && cmake --build build && ./build/detector_test"
      # - name: install libs
      #   run: bash .github/detector.sh

      # - name: test project building
      #   run: |
      #     cmake -S . -B build
      #     cmake --build build

      # - name: detector tests
      #   run: |
      #     ./build/detector_test